# Generated by Django 6.0.7 on 2026-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='timeline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
