# Generated by Django 6.0.7 on 2026-07-28 11:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trip', '0003_trip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripUser',
            fields=[
            ],
            options={
                'verbose_name': 'User (and their Trips)',
                'verbose_name_plural': 'Users (and their Trips)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='log_sheets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
